-- ALTER TABLES

SELECT * FROM students;

-- ADD NEW COLUMNS
ALTER TABLE students ADD COLUMN age INT;
ALTER TABLE students ADD COLUMN age INT DEFAULT 0;

-- DELETE COLUMN
ALTER TABLE students DROP COLUMN age;

-- RENAME COLUMN NAME
ALTER TABLE students RENAME COLUMN name TO full_name;

-- MODIFY COLUMN TYPE

ALTER TABLE students COLUMN age SET DECIMAL;

